#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config window_placement              first_child 
yabai -m config split_ratio 0.5

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5 
yabai -m config bottom_padding               5
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6


yabai -m config window_animation_duration    0.00
yabai -m config auto_balance                 off


#mouse settings
yabai -m config mouse_follows_focus          on
yabai -m config mouse_modifier               alt 
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config window_shadow off
yabai -m config window_border_width 0
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# yabai -m rule --add app="^System Settings*" manage=off

# sketchybar events (.yabairc)
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal -add event=window_minimized action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

yabai -m config external_bar all:32:0

# borders setup janky border
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=6.0 &


echo "yabai configuration loaded.."
